version: '3.5'

services:
  weaviate:
    container_name: einstein_weaviate
    image: semitechnologies/weaviate:1.21.2
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,generative-openai'
      OPENAI_APIKEY: '${OPENAI_API_KEY}'  # For use with OpenAI. Setting this parameter is optional; you can also provide the key at runtime.
      # OPENAI_ORGANIZATION: einstein  # For use with OpenAI. Setting this parameter is optional; you can also provide the key at runtime.
      # AZURE_APIKEY: sk-foobar  # For use with Azure OpenAI. Setting this parameter is optional; you can also provide the key at runtime.
      CLUSTER_HOSTNAME: 'node1'
    volumes:
       - weaviate:/var/lib/weaviate
    ports:
      - "${WEAVIATE_PORT:-8080}:8080"
    restart: unless-stopped
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http

volumes:
  weaviate: