version: '3.5'

services:
  weviate:
    container_name: einstein_weviate
    image: semitechnologies/weaviate:1.21.2
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-openai,generative-openai,qna-openai'
      # CLUSTER_HOSTNAME: 'cluster1'
    volumes:
       - weviate:/var/lib/weviate
    ports:
      - "${WEVIATE_PORT:-8080}:8080"
    restart: unless-stopped
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http

volumes:
  weviate: